### ISSUE TITLE
comment in twigs

### ISSUE THREAD

**Issue by robbee** [twigy/twigy-server#3]
Hello Christian

Je suis bloqué sur un truc a la noix.. Je t'explique ce que je veux faire.. un peu comme la dernière fois quand tu avais associé _LE_ helper au twig. La l'idée c'est d'associé _LES_ commentaires au twig.

La différence c'est qu'il y a plusieurs commentaires pour un twig.. et le problème avec la hash c'est qu'il va me garder uniquement les id uniques... (tu vois ?) Je pense qu'il faudrait un tableau.. mais je n''y arrive pas :(

Je te reexplique d'une autre façon :
- dans l'event que je recupère de google j'ai un eventId et dans ma table de commentaire j'ai un eventId aussi
- si je comprends. On récupère les events depusi GG puis les comment depuis PG. Avec le comment on fait un hash avec l'eventId comme cle du hash. Puis on ajout les comments a l'extendedProperties de l'event (comme pour le helper) en matchant la cle du hash et l'eventId de event GG
- le probleme c'est que le hash me degage les comment ayant la meme cle (normal) et du coup je n'ai qu'un commentaire par twig

Bon.. c'est pas simple a expliquer.. tu peux m'appeler si tu veux des explications ;-)

Bonne soirée !!

et merci !!

PS: Pour simplifier la compréhension... tu noteras que l'eventId dans la table "comment" s'appelle le twig_id ;-)

**Comment by cblavier** [comment]
Désolé d’avoir pris autant de temps à regarder le problème.
Je viens de commiter un truc, dis moi si c’est ça que tu veux (pour chaque
clé dans le hash on stock un tableau de comments et non plus un comment
simple)

Activé 26 mai 2016 à 22:49:20, Robbee (notifications@github.com) a écrit:

Hello Christian

Je suis bloqué sur un truc a la noix.. Je t'explique ce que je veux faire..
un peu comme la dernière fois quand tu avais associé *LE* helper au twig.
La l'idée c'est d'associé *LES* commentaires au twig.

La différence c'est qu'il y a plusieurs commentaires pour un twig.. et le
problème avec la hash c'est qu'il va me garder uniquement les id uniques...
(tu vois ?) Je pense qu'il faudrait un tableau.. mais je n''y arrive pas :(

Je te reexplique d'une autre façon :

   - dans l'event que je recupère de google j'ai un eventId et dans ma
   table de commentaire j'ai un eventId aussi
   - si je comprends. On récupère les events depusi GG puis les comment
   depuis PG. Avec le comment on fait un hash avec l'eventId comme cle du
   hash. Puis on ajout les comments a l'extendedProperties de l'event (comme
   pour le helper) en matchant la cle du hash et l'eventId de event GG
   - le probleme c'est que le hash me degage les comment ayant la meme cle
   (normal) et du coup je n'ai qu'un commentaire par twig

Bon.. c'est pas simple a expliquer.. tu peux m'appeler si tu veux des
explications ;-)

Bonne soirée !!

et merci !!

PS: Pour simplifier la compréhension... tu noteras que l'eventId dans la
table "comment" s'appelle le twig_id ;-)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/twigy/twigy-server/issues/3>

**Comment by robbee** [comment]
C'est exactement ca !! Parfait !! Merci bcp
